name: Run Tests

on:
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-run-tests
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Install Dependencies
        working-directory: lambda
        run: npm ci

      - name: Build Application
        working-directory: lambda
        run: npm run build

      - name: Test Application
        working-directory: lambda
        run: npm test